dist: easy_check
language: python
python:
  - "3.7.0"  # 3.7 development branch
# command to install dependencies
#before_install:
#  - sudo apt-get install -y openssl
install:
#  - export LDFLAGS="-L/usr/local/openssl/lib"
#  - export CPPFLAGS="-I/usr/local/openssl/include"
#  - export PKG_CONFIG_PATH="/usr/local/openssl/lib/pkgconfig"
#  - sudo apt-get install -y nss
  - sudo pip install coveralls
  - sudo apt-get install libghc-gnutls-dev
  - whereis gnutls
  - export PYCURL_SSL_LIBRARY=gnutls
  - pip install pycurl
  - python setup.py install
#virtualenv:
#  system_site_packages: true
# command to run tests
script:
  - pytest

after_success:
  - coveralls